### ISSUE TITLE
Imágenes de speakers están stretched

### ISSUE THREAD

**Issue by irojasag** [angularhonduras/ng-conf-honduras#5]
Si va a https://ng-honduras.org/speakers y revisa las fotos de los speakers, hay algunos que tienen la foto desfigurada, esto pasa porque se espera que la foto tenga el mismo width y height, pero si no lo es se intenta ajustar y no se ven bien.

La solución ( ya que se usa tailwind css ) es añadir la clase `object-cover` en  la imagen en `src/app/views/components/speaker-card/speaker-card.component.html:5`

Aquí un antes y un después de ese cambio
Antes:
<img width="1260" alt="Antes" src="https://user-images.githubusercontent.com/18739832/109840855-1e059200-7c0e-11eb-9db0-95ebef9942b4.png">

Después:
<img width="1233" alt="Después" src="https://user-images.githubusercontent.com/18739832/109840906-28279080-7c0e-11eb-8169-511057142f35.png">

PD: Quería hacer un pull request con este fix, pero no tengo permisos en el repositorio para subir mi branch.

**Comment by ricardochl** [comment]
Gracias @irojasag el repo esta publico, creo que si deberías poder enviar tu PR.

**Comment by ricardochl** [comment]
Se realizo el PR para corregir el issue.
